name: main

on:
  push:

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Magento 2
        run: |
          composer config http-basic.repo.magento.com ${{ secrets.MAG_MARKETPLACE_USERNAME }} ${{ secrets.MAG_MARKETPLACE_PASSWORD }}
          mkdir ./../mag2
          composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./../mag2

      - name: PHPUnit preparation
        run: |
          mkdir -p ./../mag2/app/code/Coddin/CartBridge
          cp -r src/* ./../mag2/app/code/Coddin/CartBridge

      - name: PHPUnit
        run: ./../mag2/vendor/bin/phpunit -c ./../mag2/dev/tests/unit/phpunit.xml.dist ./../mag2/app/code/Coddin/CartBridge/Test/Unit --coverage-clover clover.xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./../mag2/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
